CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  site_role text NOT NULL DEFAULT 'member',
  access_revoked boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_site_role_check CHECK (site_role IN ('owner', 'manager', 'member'))
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS site_role text NOT NULL DEFAULT 'member';
ALTER TABLE users ADD COLUMN IF NOT EXISTS access_revoked boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE users ALTER COLUMN site_role SET DEFAULT 'member';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'users'
      AND column_name = 'access_status'
  ) THEN
    UPDATE users
    SET access_revoked = true
    WHERE access_status = 'revoked';
  END IF;
END $$;

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_site_role_check;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_access_status_check;

UPDATE users
SET site_role = CASE
  WHEN site_role IN ('owner', 'manager') THEN site_role
  ELSE 'member'
END;

ALTER TABLE users ADD CONSTRAINT users_site_role_check CHECK (site_role IN ('owner', 'manager', 'member'));

UPDATE users
SET site_role = 'owner', access_revoked = false
WHERE id = (
  SELECT id FROM users ORDER BY id ASC LIMIT 1
)
AND NOT EXISTS (
  SELECT 1 FROM users WHERE site_role IN ('owner', 'manager')
);

CREATE TABLE IF NOT EXISTS projects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  location text,
  description text,
  notes text NOT NULL DEFAULT '',
  project_status text NOT NULL DEFAULT 'active',
  completed_at timestamptz,
  archived_at timestamptz,
  start_date date NOT NULL,
  end_date date NOT NULL,
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT projects_date_order CHECK (end_date >= start_date),
  CONSTRAINT projects_project_status_check CHECK (project_status IN ('active', 'completed', 'archived'))
);

ALTER TABLE projects ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT '';
UPDATE projects SET notes = '' WHERE notes IS NULL;
ALTER TABLE projects ALTER COLUMN notes SET DEFAULT '';
ALTER TABLE projects ALTER COLUMN notes SET NOT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS project_status text NOT NULL DEFAULT 'active';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS completed_at timestamptz;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS archived_at timestamptz;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'projects_project_status_check'
  ) THEN
    ALTER TABLE projects ADD CONSTRAINT projects_project_status_check CHECK (project_status IN ('active', 'completed', 'archived'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS project_members (
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'viewer',
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, user_id),
  CONSTRAINT project_members_role_check CHECK (role IN ('owner', 'manager', 'editor', 'viewer'))
);

CREATE TABLE IF NOT EXISTS tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  parent_task_id integer REFERENCES tasks(id) ON DELETE SET NULL,
  name text NOT NULL,
  description text,
  trade text,
  vendor text,
  vendor_secondary text,
  security_team_member text,
  pm text,
  assigned_to integer REFERENCES users(id) ON DELETE SET NULL,
  assignee_secondary text,
  assignee_tertiary text,
  assignee_quaternary text,
  status text NOT NULL DEFAULT 'not_started',
  priority text NOT NULL DEFAULT 'normal',
  start_date date NOT NULL,
  end_date date NOT NULL,
  percent_complete integer NOT NULL DEFAULT 0,
  color text NOT NULL DEFAULT '#2563eb',
  sort_order integer NOT NULL DEFAULT 0,
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tasks_status_check CHECK (status IN ('not_started', 'in_progress', 'blocked', 'complete')),
  CONSTRAINT tasks_priority_check CHECK (priority IN ('low', 'normal', 'high', 'critical')),
  CONSTRAINT tasks_trade_check CHECK (trade IS NULL OR trade IN ('CCure', 'Cameras', 'CCure & Cameras')),
  CONSTRAINT tasks_security_team_member_check CHECK (security_team_member IS NULL OR security_team_member IN ('Derick', 'Eric', 'James', 'Justin', 'Kenna', 'Kyra', 'Ryan', 'Suvam')),
  CONSTRAINT tasks_pm_check CHECK (pm IS NULL OR pm IN ('Kurt', 'Austin')),
  CONSTRAINT tasks_vendor_check CHECK (vendor IS NULL OR vendor IN ('Accent Automatic', 'Beacon', 'Convergint', 'DSI', 'G4S', 'IC&E', 'Ideacom', 'IES', 'Nelson Fire', 'OTIS', 'Pavion', 'Pye Barker', 'S101', 'SMT', 'Stone Security', 'USHOP')),
  CONSTRAINT tasks_progress_check CHECK (percent_complete >= 0 AND percent_complete <= 100),
  CONSTRAINT tasks_date_order CHECK (end_date >= start_date)
);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS trade text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS vendor text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS vendor_secondary text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS security_team_member text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS pm text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assignee_secondary text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assignee_tertiary text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assignee_quaternary text;

UPDATE tasks SET trade = NULL WHERE trade IS NOT NULL AND trade NOT IN ('CCure', 'Cameras', 'CCure & Cameras');
UPDATE tasks SET vendor = NULL WHERE vendor IS NOT NULL AND vendor NOT IN ('Accent Automatic', 'Beacon', 'Convergint', 'DSI', 'G4S', 'IC&E', 'Ideacom', 'IES', 'Nelson Fire', 'OTIS', 'Pavion', 'Pye Barker', 'S101', 'SMT', 'Stone Security', 'USHOP');
UPDATE tasks SET security_team_member = NULL WHERE security_team_member IS NOT NULL AND security_team_member NOT IN ('Derick', 'Eric', 'James', 'Justin', 'Kenna', 'Kyra', 'Ryan', 'Suvam');
UPDATE tasks SET pm = NULL WHERE pm IS NOT NULL AND pm NOT IN ('Kurt', 'Austin');

ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_trade_check;
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_vendor_check;
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_security_team_member_check;
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_pm_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_trade_check CHECK (trade IS NULL OR trade IN ('CCure', 'Cameras', 'CCure & Cameras'));
ALTER TABLE tasks ADD CONSTRAINT tasks_vendor_check CHECK (vendor IS NULL OR vendor IN ('Accent Automatic', 'Beacon', 'Convergint', 'DSI', 'G4S', 'IC&E', 'Ideacom', 'IES', 'Nelson Fire', 'OTIS', 'Pavion', 'Pye Barker', 'S101', 'SMT', 'Stone Security', 'USHOP'));
ALTER TABLE tasks ADD CONSTRAINT tasks_security_team_member_check CHECK (security_team_member IS NULL OR security_team_member IN ('Derick', 'Eric', 'James', 'Justin', 'Kenna', 'Kyra', 'Ryan', 'Suvam'));
ALTER TABLE tasks ADD CONSTRAINT tasks_pm_check CHECK (pm IS NULL OR pm IN ('Kurt', 'Austin'));

CREATE TABLE IF NOT EXISTS task_dependencies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  predecessor_task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  successor_task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  type text NOT NULL DEFAULT 'FS',
  lag_days integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT task_dependencies_type_check CHECK (type IN ('FS', 'SS', 'FF', 'SF')),
  CONSTRAINT task_dependencies_no_self CHECK (predecessor_task_id <> successor_task_id),
  UNIQUE (project_id, predecessor_task_id, successor_task_id, type)
);

CREATE TABLE IF NOT EXISTS task_comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  user_id integer REFERENCES users(id) ON DELETE SET NULL,
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS project_note_entries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  body text NOT NULL,
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  updated_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE project_note_entries ADD COLUMN IF NOT EXISTS updated_by integer REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE project_note_entries ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE project_note_entries ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename = 'project_note_entries' AND indexname = 'idx_project_note_entries_project_created') THEN
    CREATE INDEX idx_project_note_entries_project_created ON project_note_entries (project_id, created_at DESC, id DESC);
  END IF;
END $$;

DO $$
BEGIN
  INSERT INTO project_note_entries (project_id, body, created_by, updated_by, created_at, updated_at)
  SELECT p.id, p.notes, p.created_by, p.created_by, coalesce(p.updated_at, now()), coalesce(p.updated_at, now())
  FROM projects p
  WHERE coalesce(p.notes, '') <> ''
    AND NOT EXISTS (SELECT 1 FROM project_note_entries pne WHERE pne.project_id = p.id);
EXCEPTION
  WHEN duplicate_table THEN
    NULL;
END $$;

CREATE TABLE IF NOT EXISTS project_checklist_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  item_key text NOT NULL,
  label text NOT NULL,
  is_checked boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  updated_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (project_id, item_key)
);

-- Upgrade older PSG and SS Tracking databases that created this table before sort_order,
-- updated_by, created_at, or id existed. This keeps Render redeploys safe.
DO $$
DECLARE
  checklist_id_is_identity text;
BEGIN
  SELECT is_identity
  INTO checklist_id_is_identity
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'project_checklist_items'
    AND column_name = 'id';

  IF checklist_id_is_identity IS NULL THEN
    ALTER TABLE project_checklist_items ADD COLUMN id integer;
    checklist_id_is_identity := 'NO';
  END IF;

  IF checklist_id_is_identity = 'NO' THEN
    CREATE SEQUENCE IF NOT EXISTS project_checklist_items_id_seq;
    ALTER SEQUENCE project_checklist_items_id_seq OWNED BY project_checklist_items.id;
    ALTER TABLE project_checklist_items ALTER COLUMN id SET DEFAULT nextval('project_checklist_items_id_seq');
    UPDATE project_checklist_items SET id = nextval('project_checklist_items_id_seq') WHERE id IS NULL;
    PERFORM setval('project_checklist_items_id_seq', GREATEST((SELECT COALESCE(MAX(id), 0) FROM project_checklist_items), 1), true);
    ALTER TABLE project_checklist_items ALTER COLUMN id SET NOT NULL;
  END IF;
END $$;

ALTER TABLE project_checklist_items ADD COLUMN IF NOT EXISTS sort_order integer;
UPDATE project_checklist_items
SET sort_order = CASE item_key
  WHEN 'ips_requested' THEN 1
  WHEN 'panel_ordered' THEN 2
  WHEN 'clearances_programmed' THEN 3
  WHEN 'doors_programmed' THEN 4
  WHEN 'ccure_operator_established' THEN 5
  ELSE COALESCE(sort_order, 0)
END
WHERE sort_order IS NULL OR sort_order = 0;
ALTER TABLE project_checklist_items ALTER COLUMN sort_order SET DEFAULT 0;
ALTER TABLE project_checklist_items ALTER COLUMN sort_order SET NOT NULL;

ALTER TABLE project_checklist_items ADD COLUMN IF NOT EXISTS updated_by integer REFERENCES users(id) ON DELETE SET NULL;
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'project_checklist_items'
      AND column_name = 'checked_by'
  ) THEN
    UPDATE project_checklist_items
    SET updated_by = checked_by
    WHERE updated_by IS NULL AND checked_by IS NOT NULL;
  END IF;
END $$;

ALTER TABLE project_checklist_items ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
UPDATE project_checklist_items SET created_at = now() WHERE created_at IS NULL;
ALTER TABLE project_checklist_items ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE project_checklist_items ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE project_checklist_items ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
UPDATE project_checklist_items SET updated_at = now() WHERE updated_at IS NULL;
ALTER TABLE project_checklist_items ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE project_checklist_items ALTER COLUMN updated_at SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_project_checklist_items_id_unique ON project_checklist_items(id);

CREATE TABLE IF NOT EXISTS project_blueprints (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  original_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes integer NOT NULL CHECK (size_bytes > 0),
  file_data bytea NOT NULL,
  uploaded_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Upgrade older blueprint tables that used file_name/file_size column names.
ALTER TABLE project_blueprints ADD COLUMN IF NOT EXISTS original_name text;
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'project_blueprints'
      AND column_name = 'file_name'
  ) THEN
    UPDATE project_blueprints
    SET original_name = file_name
    WHERE original_name IS NULL AND file_name IS NOT NULL;
  END IF;
END $$;
UPDATE project_blueprints SET original_name = concat('blueprint-', id) WHERE original_name IS NULL;
ALTER TABLE project_blueprints ALTER COLUMN original_name SET NOT NULL;

ALTER TABLE project_blueprints ADD COLUMN IF NOT EXISTS size_bytes integer;
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'project_blueprints'
      AND column_name = 'file_size'
  ) THEN
    UPDATE project_blueprints
    SET size_bytes = file_size
    WHERE size_bytes IS NULL AND file_size IS NOT NULL;
  END IF;
END $$;
UPDATE project_blueprints SET size_bytes = octet_length(file_data) WHERE size_bytes IS NULL AND file_data IS NOT NULL;
UPDATE project_blueprints SET size_bytes = 1 WHERE size_bytes IS NULL OR size_bytes <= 0;
ALTER TABLE project_blueprints ALTER COLUMN size_bytes SET NOT NULL;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'project_blueprints_size_bytes_check'
  ) THEN
    ALTER TABLE project_blueprints ADD CONSTRAINT project_blueprints_size_bytes_check CHECK (size_bytes > 0);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS audit_log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer REFERENCES projects(id) ON DELETE CASCADE,
  task_id integer REFERENCES tasks(id) ON DELETE SET NULL,
  user_id integer REFERENCES users(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id integer,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO project_checklist_items (project_id, item_key, label, sort_order)
SELECT p.id, defaults.item_key, defaults.label, defaults.sort_order
FROM projects p
CROSS JOIN (
  VALUES
    ('ips_requested', 'IPs requested', 1),
    ('panel_ordered', 'Panel ordered', 2),
    ('clearances_programmed', 'Clearances programmed', 3),
    ('doors_programmed', 'Doors programmed', 4),
    ('ccure_operator_established', 'CCure Operator established', 5)
) AS defaults(item_key, label, sort_order)
ON CONFLICT (project_id, item_key) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_users_site_role ON users(site_role, access_revoked);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(project_status);
CREATE INDEX IF NOT EXISTS idx_project_members_user ON project_members(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id, sort_order, start_date);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_task_dependencies_project ON task_dependencies(project_id);
CREATE INDEX IF NOT EXISTS idx_checklist_project ON project_checklist_items(project_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_blueprints_project ON project_blueprints(project_id, created_at DESC);

CREATE TABLE IF NOT EXISTS owner_cms_work_orders (
  sheet_key text PRIMARY KEY,
  sheet_name text NOT NULL,
  cells jsonb NOT NULL DEFAULT '[]'::jsonb,
  archived_cells jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO owner_cms_work_orders (sheet_key, sheet_name, cells)
VALUES
  ('kurts_cms_wos', 'Kurts CMS WOs', '[]'::jsonb),
  ('austins_cms_wos', 'Austins CMS WOs', '[]'::jsonb)
ON CONFLICT (sheet_key) DO UPDATE SET
  sheet_name = EXCLUDED.sheet_name;

ALTER TABLE owner_cms_work_orders ADD COLUMN IF NOT EXISTS archived_cells jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_owner_cms_work_orders_sheet_key ON owner_cms_work_orders(sheet_key);
CREATE INDEX IF NOT EXISTS idx_audit_log_project ON audit_log(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_task_comments_task ON task_comments(task_id, created_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_projects_updated_at ON projects;
CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_tasks_updated_at ON tasks;
CREATE TRIGGER trg_tasks_updated_at
BEFORE UPDATE ON tasks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_project_checklist_items_updated_at ON project_checklist_items;
DROP TRIGGER IF EXISTS trg_project_checklist_updated_at ON project_checklist_items;
CREATE TRIGGER trg_project_checklist_updated_at
BEFORE UPDATE ON project_checklist_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_owner_cms_work_orders_updated_at ON owner_cms_work_orders;
CREATE TRIGGER trg_owner_cms_work_orders_updated_at
BEFORE UPDATE ON owner_cms_work_orders
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS project_invite_codes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  code text NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'viewer',
  max_uses integer NOT NULL DEFAULT 10 CHECK (max_uses > 0 AND max_uses <= 100),
  uses_count integer NOT NULL DEFAULT 0 CHECK (uses_count >= 0),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  target_user_id integer REFERENCES users(id) ON DELETE SET NULL,
  target_email text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT project_invite_codes_role_check CHECK (role IN ('manager', 'editor', 'viewer'))
);

ALTER TABLE project_invite_codes ADD COLUMN IF NOT EXISTS target_user_id integer REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE project_invite_codes ADD COLUMN IF NOT EXISTS target_email text;

CREATE INDEX IF NOT EXISTS idx_project_invite_codes_project ON project_invite_codes(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_invite_codes_code ON project_invite_codes(code);
CREATE INDEX IF NOT EXISTS idx_project_invite_codes_target_user ON project_invite_codes(target_user_id);
