CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  site_role text NOT NULL DEFAULT 'viewer',
  access_status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_site_role_check CHECK (site_role IN ('owner', 'manager', 'editor', 'viewer')),
  CONSTRAINT users_access_status_check CHECK (access_status IN ('active', 'revoked'))
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS site_role text NOT NULL DEFAULT 'viewer';
ALTER TABLE users ADD COLUMN IF NOT EXISTS access_status text NOT NULL DEFAULT 'active';
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'users_site_role_check'
  ) THEN
    ALTER TABLE users ADD CONSTRAINT users_site_role_check CHECK (site_role IN ('owner', 'manager', 'editor', 'viewer'));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'users_access_status_check'
  ) THEN
    ALTER TABLE users ADD CONSTRAINT users_access_status_check CHECK (access_status IN ('active', 'revoked'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS projects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  location text,
  description text,
  project_status text NOT NULL DEFAULT 'active',
  start_date date NOT NULL,
  end_date date NOT NULL,
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT projects_date_order CHECK (end_date >= start_date),
  CONSTRAINT projects_project_status_check CHECK (project_status IN ('active', 'completed'))
);

ALTER TABLE projects ADD COLUMN IF NOT EXISTS project_status text NOT NULL DEFAULT 'active';
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'projects_project_status_check'
  ) THEN
    ALTER TABLE projects ADD CONSTRAINT projects_project_status_check CHECK (project_status IN ('active', 'completed'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS project_members (
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'viewer',
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, user_id),
  CONSTRAINT project_members_role_check CHECK (role IN ('owner', 'manager', 'editor', 'viewer'))
);

UPDATE users u
SET site_role = CASE
  WHEN EXISTS (SELECT 1 FROM project_members pm WHERE pm.user_id = u.id AND pm.role = 'owner') THEN 'owner'
  WHEN EXISTS (SELECT 1 FROM project_members pm WHERE pm.user_id = u.id AND pm.role = 'manager') THEN 'manager'
  ELSE u.site_role
END
WHERE u.site_role = 'viewer'
  AND EXISTS (SELECT 1 FROM project_members pm WHERE pm.user_id = u.id AND pm.role IN ('owner', 'manager'));

CREATE TABLE IF NOT EXISTS tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  parent_task_id integer REFERENCES tasks(id) ON DELETE SET NULL,
  name text NOT NULL,
  description text,
  trade text,
  assigned_to integer REFERENCES users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'not_started',
  priority text NOT NULL DEFAULT 'normal',
  start_date date NOT NULL,
  end_date date NOT NULL,
  percent_complete integer NOT NULL DEFAULT 0,
  color text NOT NULL DEFAULT '#2563eb',
  sort_order integer NOT NULL DEFAULT 0,
  created_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tasks_status_check CHECK (status IN ('not_started', 'in_progress', 'blocked', 'complete')),
  CONSTRAINT tasks_priority_check CHECK (priority IN ('low', 'normal', 'high', 'critical')),
  CONSTRAINT tasks_progress_check CHECK (percent_complete >= 0 AND percent_complete <= 100),
  CONSTRAINT tasks_date_order CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS task_dependencies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  predecessor_task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  successor_task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  type text NOT NULL DEFAULT 'FS',
  lag_days integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT task_dependencies_type_check CHECK (type IN ('FS', 'SS', 'FF', 'SF')),
  CONSTRAINT task_dependencies_no_self CHECK (predecessor_task_id <> successor_task_id),
  UNIQUE (project_id, predecessor_task_id, successor_task_id, type)
);

CREATE TABLE IF NOT EXISTS task_comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  user_id integer REFERENCES users(id) ON DELETE SET NULL,
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS project_checklist_items (
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  item_key text NOT NULL,
  label text NOT NULL,
  is_checked boolean NOT NULL DEFAULT false,
  checked_by integer REFERENCES users(id) ON DELETE SET NULL,
  checked_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, item_key),
  CONSTRAINT project_checklist_items_key_check CHECK (item_key IN ('ips_requested', 'panel_ordered', 'clearances_programmed', 'doors_programmed', 'ccure_operator_established'))
);

CREATE TABLE IF NOT EXISTS project_blueprints (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  file_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/octet-stream',
  file_size integer NOT NULL,
  file_data bytea NOT NULL,
  uploaded_by integer REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer REFERENCES projects(id) ON DELETE CASCADE,
  task_id integer REFERENCES tasks(id) ON DELETE SET NULL,
  user_id integer REFERENCES users(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id integer,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_site_role ON users(site_role);
CREATE INDEX IF NOT EXISTS idx_users_access_status ON users(access_status);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(project_status);
CREATE INDEX IF NOT EXISTS idx_project_members_user ON project_members(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id, sort_order, start_date);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_task_dependencies_project ON task_dependencies(project_id);
CREATE INDEX IF NOT EXISTS idx_project_checklist_items_project ON project_checklist_items(project_id);
CREATE INDEX IF NOT EXISTS idx_project_blueprints_project ON project_blueprints(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_project ON audit_log(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_task_comments_task ON task_comments(task_id, created_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_projects_updated_at ON projects;
CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_tasks_updated_at ON tasks;
CREATE TRIGGER trg_tasks_updated_at
BEFORE UPDATE ON tasks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_project_checklist_items_updated_at ON project_checklist_items;
CREATE TRIGGER trg_project_checklist_items_updated_at
BEFORE UPDATE ON project_checklist_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
